version: '3'
services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASS}
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
  app:
    build: .
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASS: ${NEO4J_PASS}
    depends_on:
      - neo4j

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
